name: CI
on:
  pull_request:
  push:
    branches: master
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io
  TAG_TYPES: |
    type=ref,event=branch
    type=ref,event=schedule
    type=sha,prefix=,format=long

jobs:
  base:
    runs-on: ubuntu-latest
    env:
      IMAGE: base

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE }}
          tags: ${{ env.TAG_TYPES }}

      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  buildtime:
    needs: base
    runs-on: ubuntu-latest
    env:
      IMAGE: buildtime

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE }}
          tags: ${{ env.TAG_TYPES }}

      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/base
            BASE_TAG=${{ github.sha }}
